# generated by datamodel-codegen:
#   filename:  settings.json
#   timestamp: 2024-07-29T15:15:08+00:00

from __future__ import annotations

from typing import List
from datetime import date

from pydantic import BaseModel


class Body(BaseModel):
    id: int
    name: str
    show: bool
    orbit: bool
    children: List[Body]

class Settings(BaseModel):
    startDate: date
    endDate: date
    majorBodies: List[Body]
    minorBodies: List[Body]
    missions: List[Body]

class RequestModel(BaseModel):
    startDate: date
    endDate: date
    export: bool
    bodies: List[Body]

class ResponseModel(BaseModel):
    settings: Settings
    renderData: str
